-- MySQL Script generated by MySQL Workbench
-- 07/05/18 19:17:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema notas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `notas` ;

-- -----------------------------------------------------
-- Schema notas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `notas` ;

-- -----------------------------------------------------
-- Table `notas`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`roles` (
  `rol_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(255) NOT NULL COMMENT '',
  `status` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`rol_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`usuarios` (
  `usuarios_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `rol_id` INT UNSIGNED NOT NULL COMMENT '',
  `nombre` VARCHAR(255) NOT NULL COMMENT '',
  `clave` VARCHAR(255) NOT NULL COMMENT '',
  `status` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`usuarios_id`)  COMMENT '',
  INDEX `fk_usuarios_roles1_idx` (`rol_id` ASC)  COMMENT '',
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `notas`.`roles` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`maestros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`maestros` (
  `maestro_id` INT UNSIGNED NOT NULL COMMENT '',
  `usuarios_id` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(255) NULL COMMENT '',
  `fecha_n` DATE NULL COMMENT '',
  `sexo` VARCHAR(1) NULL DEFAULT 'f' COMMENT '',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`maestro_id`)  COMMENT '',
  INDEX `fk_maestros_usuarios1_idx` (`usuarios_id` ASC)  COMMENT '',
  CONSTRAINT `fk_maestros_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `notas`.`usuarios` (`usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`periodos` (
  `periodo_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `inicio` YEAR NOT NULL COMMENT '',
  `cierre` YEAR NOT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`periodo_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`grados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`grados` (
  `grado_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`grado_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`materias` (
  `materia_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `grado_id` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(255) NOT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`materia_id`)  COMMENT '',
  INDEX `fk_materias_grados1_idx` (`grado_id` ASC)  COMMENT '',
  CONSTRAINT `fk_materias_grados1`
    FOREIGN KEY (`grado_id`)
    REFERENCES `notas`.`grados` (`grado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`literales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`literales` (
  `literal_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `grado_id` INT NOT NULL COMMENT '',
  `nota` VARCHAR(1) NOT NULL COMMENT '',
  `rango_d` INT NOT NULL COMMENT '',
  `rango_h` INT NOT NULL COMMENT '',
  `descripcion` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`literal_id`)  COMMENT '',
  INDEX `fk_literales_grados1_idx` (`grado_id` ASC)  COMMENT '',
  CONSTRAINT `fk_literales_grados1`
    FOREIGN KEY (`grado_id`)
    REFERENCES `notas`.`grados` (`grado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`cursos` (
  `curso_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `periodo_id` INT UNSIGNED NOT NULL COMMENT '',
  `grado_id` INT NOT NULL COMMENT '',
  `maestro_id` INT UNSIGNED NOT NULL COMMENT '',
  `seccion` VARCHAR(1) NOT NULL COMMENT '',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`curso_id`)  COMMENT '',
  INDEX `fk_cursos_periodos1_idx` (`periodo_id` ASC)  COMMENT '',
  INDEX `fk_cursos_grados1_idx` (`grado_id` ASC)  COMMENT '',
  INDEX `fk_cursos_maestros1_idx` (`maestro_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cursos_periodos1`
    FOREIGN KEY (`periodo_id`)
    REFERENCES `notas`.`periodos` (`periodo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_grados1`
    FOREIGN KEY (`grado_id`)
    REFERENCES `notas`.`grados` (`grado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_maestros1`
    FOREIGN KEY (`maestro_id`)
    REFERENCES `notas`.`maestros` (`maestro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`lugares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`lugares` (
  `lugar_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` TEXT NULL COMMENT '',
  PRIMARY KEY (`lugar_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`estudiantes` (
  `estudiante_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(255) NULL COMMENT '',
  `fecha_n` DATE NULL COMMENT '',
  `sexo` VARCHAR(1) NULL DEFAULT 'f' COMMENT '',
  `lugar_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`estudiante_id`)  COMMENT '',
  INDEX `fk_estudiantes_lugares1_idx` (`lugar_id` ASC)  COMMENT '',
  CONSTRAINT `fk_estudiantes_lugares1`
    FOREIGN KEY (`lugar_id`)
    REFERENCES `notas`.`lugares` (`lugar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notas`.`cursos_estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notas`.`cursos_estudiantes` (
  `curso_id` INT NOT NULL COMMENT '',
  `estudiante_id` INT UNSIGNED NOT NULL COMMENT '',
  `materia_id` INT NOT NULL COMMENT '',
  `nota` FLOAT NOT NULL DEFAULT 0 COMMENT '',
  INDEX `fk_cursos_estudiantes_cursos1_idx` (`curso_id` ASC)  COMMENT '',
  INDEX `fk_cursos_estudiantes_estudiantes1_idx` (`estudiante_id` ASC)  COMMENT '',
  INDEX `fk_cursos_estudiantes_materias1_idx` (`materia_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cursos_estudiantes_cursos1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `notas`.`cursos` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_estudiantes_estudiantes1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `notas`.`estudiantes` (`estudiante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_estudiantes_materias1`
    FOREIGN KEY (`materia_id`)
    REFERENCES `notas`.`materias` (`materia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
